clear


%%%%%%%%%%%%%%%%%%%%%%%%%%% read in data %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
profile_rutv_cpu_dat
profile_rutv_gpu_dat
times_std % library times for GPU

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% plot %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% column 7 contains the total time for the factorization
figure(1)
p1 = plot(n(1:end-1), profile_b256_q0_cpu(1:end-1,7)' ./ n(1:end-1).^3, 'k-',...
		  n(1:end-1), profile_b256_q2_cpu(1:end-1,7)' ./ n(1:end-1).^3, 'k--',...
		  n(1:end-1), profile_b256_q0_gpu(1:end-1,7)' ./ n(1:end-1).^3, 'b-',...
		  n(1:end-1), profile_b256_q2_gpu(1:end-1,7)' ./ n(1:end-1).^3, 'b--',...
		  n_std, t_svd ./ n_std.^3, 'r-',...
		  n_std, t_cpqr ./ n_std.^3, 'g-');
ax = gca;
set(ax,'fontsize',16);
set(p1,'LineWidth',2,'MarkerSize',10);
title('randUTV GPU and CPU, b=256');
xlabel('n');
ylabel('Time [s] / n^2');
legend(	'CPU, q=0',...
		'CPU, q=2',...
		'GPU, q=0',...
		'GPU, q=2',...
		'GPU SVD (MAGMA)',...
		'GPU CPQR (MAGMA)');
legend('Location', 'SouthWest');
