clear


%%%%%%%%%%%%%%%%%%%%%%%%%%% read in data %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
profile_rutv_cpu_dat
profile_rutv_gpu_dat

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% plot %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure(1)
p1 = plot(n, profile_b256_q2_cpu(:,1)' ./ profile_b256_q2_gpu(:,1)', 'k-',...
		  n, profile_b256_q2_cpu(:,2)' ./ profile_b256_q2_gpu(:,2)', 'b-',...
		  n, profile_b256_q2_cpu(:,3)' ./ profile_b256_q2_gpu(:,3)', 'g-',...
		  n, profile_b256_q2_cpu(:,4)' ./ profile_b256_q2_gpu(:,4)', 'r-',...
		  n, profile_b256_q2_cpu(:,5)' ./ profile_b256_q2_gpu(:,5)', 'c-',...
		  n, profile_b256_q2_cpu(:,6)' ./ profile_b256_q2_gpu(:,6)', 'm-',...
		  n, profile_b256_q2_cpu(:,7)' ./ profile_b256_q2_gpu(:,7)', 'k--*');
ax = gca;
set(ax,'fontsize',16);
set(p1,'LineWidth',2,'MarkerSize',10);
title('Acceleration factor for randUTV components, b=256, q=2');
xlabel('n');
ylabel('time_{CPU} / time_{GPU}');
ylim([0 10])
legend(	'build\_y',...
		'qr\_1',...
		'qr\_1\_updt\_a',...
		'qr\_2',...
		'qr\_2\_updt\_a',...
		'svd',...
		'total');
legend('Location', 'SouthWest');
