clear


%%%%%%%%%%%%%%%%%%%%%%%%%%% read in data %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
times_std
times_rutv_gpu
times_rutv_gpu_OS_ON

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% plot %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure(1);
p1 = plot(n_std, t_svd ./ (n_std.^3), 'k-',...
		n_std, t_cpqr ./ (n_std.^3), 'g-',...
		n_rutv_gpu, t_rutv_gpu(1,:) ./ (n_rutv_gpu.^3), 'ro-',...
		n_rutv_gpu, t_rutv_gpu(3,:) ./ (n_rutv_gpu.^3), 'rs--',...
		n_rutv_gpu, t_rutv_gpu(5,:) ./ (n_rutv_gpu.^3), 'rv-.',...
		n_rutv_gpu, t_rutv_gpu_os(1,:) ./ (n_rutv_gpu.^3), 'bo-',...
		n_rutv_gpu, t_rutv_gpu_os(3,:) ./ (n_rutv_gpu.^3), 'bs--',...
		n_rutv_gpu, t_rutv_gpu_os(5,:) ./ (n_rutv_gpu.^3), 'bv-.');
ax = gca;
set(ax,'fontsize',16);
set(p1,'LineWidth',2,'MarkerSize',10);
xlabel('n');
ylabel('Time [s] / n^3');
legend(	'MAGMA dgesdd (SVD)',...
		'MAGMA dgeqp3 (CPQR)',...
		'rand\_utv\_gpu, q=0, p=0',...
		'rand\_utv\_gpu, q=2, p=0',...
		'rand\_utv\_gpu, q=4, p=0',...
		'rand\_utv\_gpu, q=0, p=b',...
		'rand\_utv\_gpu, q=2, p=b',...
		'rand\_utv\_gpu, q=4, p=b');
legend('Location', 'NorthEast');
