clear

%%%%%%%%%%%%%%%%%%%%%%%%%%% read in data %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
profile_cpqr_ooc_data

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% plot %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure(1);
p1 = plot(n_cpqr_ooc, t_read_ssd ./ n_cpqr_ooc.^3, 'b-', ...
		  n_cpqr_ooc, t_write_ssd ./ n_cpqr_ooc.^3, 'r-',...
		  n_cpqr_ooc, t_flop_ssd ./ n_cpqr_ooc.^3, 'k-',...
		  n_cpqr_ooc, t_read_hdd ./ n_cpqr_ooc.^3, 'b--',...
		  n_cpqr_ooc, t_write_hdd ./ n_cpqr_ooc.^3, 'r--',...
		  n_cpqr_ooc, t_flop_hdd ./ n_cpqr_ooc.^3, 'k--');
ax = gca;
set(ax,'fontsize',16);
set(p1,'LineWidth',2,'MarkerSize',10);
xlabel('n');
ylabel('Time [s] / n^3');
title('Full factorization times, b=250')
legend(	't\_read\_ssd',...
		't\_write\_ssd',...
		't\_flop\_ssd',...
		't\_read\_hdd',...
		't\_write\_hdd',...
		't\_flop\_hdd');
legend('Location', 'East');
ax.YGrid =  'on'
